using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using DWPTS.Application.Common;
using DWPTS.Application.DTOs;
using DWPTS.Application.Features.AI;
using DWPTS.Shared.Models;

namespace DWPTS.API.Controllers;

[ApiController]
[Route("api/v1/[controller]")]
[Authorize]
public class AIController : ControllerBase
{
    private readonly IAIEngineService _aiService;
    private readonly ICurrentUserService _currentUserService;

    public AIController(IAIEngineService aiService, ICurrentUserService currentUserService)
    {
        _aiService = aiService;
        _currentUserService = currentUserService;
    }

    [HttpPost("classify")]
    public async Task<ActionResult<ApiResponse<AITaskClassificationResult>>> ClassifyTask([FromBody] AIEstimateRequest request)
    {
        var result = await _aiService.ClassifyTaskAsync(request.Description);
        return Ok(ApiResponse<AITaskClassificationResult>.Ok(result, "Task classified successfully by AI Engine"));
    }

    [HttpPost("prioritize")]
    public async Task<ActionResult<ApiResponse<List<AIPriorityRecommendation>>>> PrioritizeWork([FromBody] List<WorkEntryDto> entries, [FromQuery] decimal dailyCapacity = 8.0m)
    {
        var result = await _aiService.PrioritizeDailyWorkAsync(entries, dailyCapacity);
        return Ok(ApiResponse<List<AIPriorityRecommendation>>.Ok(result, "Daily priorities generated by AI"));
    }

    [HttpPost("plan")]
    public async Task<ActionResult<ApiResponse<List<AIPlanDraftItem>>>> ParsePlan([FromBody] AIPlanRequest request)
    {
        var result = await _aiService.ParsePlanNotesAsync(request.NaturalLanguageNotes);
        return Ok(ApiResponse<List<AIPlanDraftItem>>.Ok(result, "Draft work items parsed from natural language"));
    }

    [HttpPost("estimate")]
    public async Task<ActionResult<ApiResponse<AIEstimateResult>>> EstimateEffort([FromBody] AIEstimateRequest request)
    {
        var result = await _aiService.EstimateEffortAsync(request);
        return Ok(ApiResponse<AIEstimateResult>.Ok(result, "Effort estimated based on historical task distribution"));
    }

    [HttpPost("ask")]
    public async Task<ActionResult<ApiResponse<AIAskQueryResult>>> AskDwpts([FromBody] AIAskQueryRequest request)
    {
        var role = _currentUserService.Role ?? "EMPLOYEE";
        var user = _currentUserService.Username ?? "user";
        var result = await _aiService.AskDwptsAsync(request.NaturalLanguageQuery, role, user);
        return Ok(ApiResponse<AIAskQueryResult>.Ok(result, "Query executed with authorized multi-tenant scoping"));
    }

    [HttpGet("executive-summary")]
    public async Task<ActionResult<ApiResponse<AIExecutiveSummaryResult>>> GetExecutiveSummary([FromQuery] string? period = null)
    {
        var result = await _aiService.GenerateExecutiveSummaryAsync(period ?? "Current Cycle");
        return Ok(ApiResponse<AIExecutiveSummaryResult>.Ok(result, "Executive summary generated"));
    }

    [HttpPost("rag/query")]
    public async Task<ActionResult<ApiResponse<RAGQueryResult>>> QueryKnowledgeBase([FromBody] RAGQueryRequest request)
    {
        var result = await _aiService.QueryKnowledgeBaseAsync(request.Query);
        return Ok(ApiResponse<RAGQueryResult>.Ok(result, "Grounded answer retrieved with source citation"));
    }

    [HttpGet("rag/documents")]
    public async Task<ActionResult<ApiResponse<List<RAGDocument>>>> GetKnowledgeDocuments()
    {
        var result = await _aiService.GetKnowledgeDocumentsAsync();
        return Ok(ApiResponse<List<RAGDocument>>.Ok(result, "Knowledge documents retrieved"));
    }

    [HttpPost("rag/upload")]
    [Authorize(Policy = "RequireAdmin")]
    public async Task<ActionResult<ApiResponse<RAGDocument>>> UploadKnowledgeDocument([FromBody] RAGDocument doc)
    {
        var result = await _aiService.AddKnowledgeDocumentAsync(doc.Title, doc.Category, doc.Content, doc.Section);
        return Ok(ApiResponse<RAGDocument>.Ok(result, "Document indexed in RAG knowledge repository"));
    }

    [HttpGet("telemetry")]
    public async Task<ActionResult<ApiResponse<AITelemetryMetrics>>> GetTelemetry()
    {
        var result = await _aiService.GetTelemetryMetricsAsync();
        return Ok(ApiResponse<AITelemetryMetrics>.Ok(result, "AI usage & token cost telemetry"));
    }
}
